# Generated by Django 4.2.7 on 2025-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtest',
            name='parsed_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
