# Generated by Django 4.2.7 on 2025-07-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wordtest_parsed_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtest',
            name='doc_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='wordtest',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
