# Generated by Django 4.2.7 on 2025-07-04 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wordtest_doc_file_alter_wordtest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordtest',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
